server:
  port: 8080
spring:
  datasource:
    druid:
      one:
        url: jdbc:h2:mem:db1
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      two:
        url: jdbc:h2:mem:db2
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      three:
        url: jdbc:h2:mem:db3
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      four:
        url: jdbc:h2:mem:db4
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      five:
        url: jdbc:h2:mem:db5
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      six:
        url: jdbc:h2:mem:db6
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      seven:
        url: jdbc:h2:mem:db7
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      eight:
        url: jdbc:h2:mem:db8
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      nine:
        url: jdbc:h2:mem:db9
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      ten:
        url: jdbc:h2:mem:db10
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000

logging:
  level:
    com.example.multi.datasource.demo: debug